services:
  - name: frontend
    path: ./frontend
    public: true
    dockerfile: ./frontend/Dockerfile
    aarepo: 592311462240.dkr.ecr.eu-west-2.amazonaws.com/mds/dev/cyberopoly-frontend
    # hack below to support html only site
    origin: lovable]e
    dependsOn:
      private:
        - backend
  - name: backend
    path: ./backend
    public: false
    aarepo: 592311462240.dkr.ecr.eu-west-2.amazonaws.com/mds/dev/cyberopoly-backend
    env:
      - ANTHROPIC_API_KEY
      - FRONTEND_URL

